In [1]:
from sqlalchemy import create_engine
import pandas as pd

In [2]:
engine1 = create_engine(
    "mysql+pymysql://root:piit2025@localhost:3306/piit"
)

In [3]:
df_emp = pd.read_sql("SELECT * FROM emp", engine1)

In [4]:
df_emp

    empno    ename        job     mgr    hiredate     sal    comm  deptno
0    1234  Taheera    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    7369    SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
2    7499    ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
3    7521     WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4    7566    JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
5    7654   MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
6    7698    BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
7    7782    CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
8    7788    SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
9    7839     KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
10   7844   TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
11   7876    ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
12   7900    JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
13   7902     FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
14   7934   MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [5]:
df_dept = pd.read_sql("SELECT * FROM dept", engine1)

In [6]:
df_dept

   deptno       dname       loc
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [7]:
# Join two tables
query = """
SELECT e.empno,
       e.ename,
       e.job,
       e.sal,
       d.dname,
       d.loc
FROM emp e
JOIN dept d
ON e.deptno = d.deptno
"""

In [8]:
empdept = pd.read_sql(query, engine1)

In [9]:
empdept

    empno    ename        job     sal       dname       loc
0    1234  Taheera    ANALYST  5000.0  ACCOUNTING  NEW YORK
1    7782    CLARK    MANAGER  2450.0  ACCOUNTING  NEW YORK
2    7839     KING  PRESIDENT  5000.0  ACCOUNTING  NEW YORK
3    7934   MILLER      CLERK  1300.0  ACCOUNTING  NEW YORK
4    7369    SMITH      CLERK   800.0    RESEARCH    DALLAS
5    7566    JONES    MANAGER  2975.0    RESEARCH    DALLAS
6    7788    SCOTT    ANALYST  3000.0    RESEARCH    DALLAS
7    7876    ADAMS      CLERK  1100.0    RESEARCH    DALLAS
8    7902     FORD    ANALYST  3000.0    RESEARCH    DALLAS
9    7499    ALLEN   SALESMAN  1600.0       SALES   CHICAGO
10   7521     WARD   SALESMAN  1250.0       SALES   CHICAGO
11   7654   MARTIN   SALESMAN  1250.0       SALES   CHICAGO
12   7698    BLAKE    MANAGER  2850.0       SALES   CHICAGO
13   7844   TURNER   SALESMAN  1500.0       SALES   CHICAGO
14   7900    JAMES      CLERK   950.0       SALES   CHICAGO

In [19]:
# 1. Names of analysts and salesmen
empdept[
    empdept['job'].isin(['ANALYST', 'SALESMAN'])
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
0,1234,Taheera,ANALYST,7839.0,1988-12-17,100.0,5000.0,10,ACCOUNTING,NEW YORK
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
8,7902,FORD,ANALYST,7566.0,1981-12-03,NaN,3000.0,20,RESEARCH,DALLAS
9,7499,ALLEN,SALESMAN,7698.0,1981-02-20,300.0,1600.0,30,SALES,CHICAGO
10,7521,WARD,SALESMAN,7698.0,1981-02-22,500.0,1250.0,30,SALES,CHICAGO
11,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1400.0,1250.0,30,SALES,CHICAGO
13,7844,TURNER,SALESMAN,7698.0,1981-09-08,0.0,1500.0,30,SALES,CHICAGO

In [11]:
# Only names
empdept[
    empdept['job'].isin(['ANALYST', 'SALESMAN'])
]['ename']

0     Taheera
6       SCOTT
8        FORD
9       ALLEN
10       WARD
11     MARTIN
13     TURNER
Name: ename, dtype: object

In [14]:
# Join two tables with all the coloumns
query = """
SELECT e.empno,
       e.ename,
       e.job,
       e.mgr,
       e.hiredate,
       e.comm,
       e.sal,
       e.deptno,
       d.dname,
       d.loc
FROM emp e
JOIN dept d
ON e.deptno = d.deptno
"""

empdept = pd.read_sql(query, engine1)

empdept

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
0,1234,Taheera,ANALYST,7839.0,1988-12-17,100.0,5000.0,10,ACCOUNTING,NEW YORK
1,7782,CLARK,MANAGER,7839.0,1981-06-09,NaN,2450.0,10,ACCOUNTING,NEW YORK
2,7839,KING,PRESIDENT,NaN,1981-11-17,NaN,5000.0,10,ACCOUNTING,NEW YORK
3,7934,MILLER,CLERK,7782.0,1982-01-23,NaN,1300.0,10,ACCOUNTING,NEW YORK
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
5,7566,JONES,MANAGER,7839.0,1981-04-02,NaN,2975.0,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
7,7876,ADAMS,CLERK,7788.0,1987-05-23,NaN,1100.0,20,RESEARCH,DALLAS
8,7902,FORD,ANALYST,7566.0,1981-12-03,NaN,3000.0,20,RESEARCH,DALLAS
9,7499,ALLEN,SALESMAN,7698.0,1981-02-20,300.0,1600.0,30,SALES,CHICAGO
10,7521,WARD,SALESMAN,7698.0,1981-02-22,500.0,1250.0,30,SALES,CHICAGO
11,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1400.0,1250.0,30,SALES,CHICAGO
12,7698,BLAKE,MANAGER,7839.0,1981-05-01,NaN,2850.0,30,SALES,CHICAGO
13,7844,TURNER,SALESMAN,7698.0,1981-09-08,0.0,1500.0,30,SALES,CHICAGO
14,7900,JAMES,CLERK,7698.0,1981-12-03,NaN,950.0,30,SALES,CHICAGO

In [18]:
# 2. Details of employees who have joined before 30 September 1981
empdept['hiredate'] = pd.to_datetime(empdept['hiredate'])

empdept[
    empdept['hiredate'] < '1981-09-30'
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
1,7782,CLARK,MANAGER,7839.0,1981-06-09,NaN,2450.0,10,ACCOUNTING,NEW YORK
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
5,7566,JONES,MANAGER,7839.0,1981-04-02,NaN,2975.0,20,RESEARCH,DALLAS
9,7499,ALLEN,SALESMAN,7698.0,1981-02-20,300.0,1600.0,30,SALES,CHICAGO
10,7521,WARD,SALESMAN,7698.0,1981-02-22,500.0,1250.0,30,SALES,CHICAGO
11,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1400.0,1250.0,30,SALES,CHICAGO
12,7698,BLAKE,MANAGER,7839.0,1981-05-01,NaN,2850.0,30,SALES,CHICAGO
13,7844,TURNER,SALESMAN,7698.0,1981-09-08,0.0,1500.0,30,SALES,CHICAGO

In [20]:
# 3. Names of employees who are not managers
empdept[
    empdept['job'] != 'MANAGER'
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
0,1234,Taheera,ANALYST,7839.0,1988-12-17,100.0,5000.0,10,ACCOUNTING,NEW YORK
2,7839,KING,PRESIDENT,NaN,1981-11-17,NaN,5000.0,10,ACCOUNTING,NEW YORK
3,7934,MILLER,CLERK,7782.0,1982-01-23,NaN,1300.0,10,ACCOUNTING,NEW YORK
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
7,7876,ADAMS,CLERK,7788.0,1987-05-23,NaN,1100.0,20,RESEARCH,DALLAS
8,7902,FORD,ANALYST,7566.0,1981-12-03,NaN,3000.0,20,RESEARCH,DALLAS
9,7499,ALLEN,SALESMAN,7698.0,1981-02-20,300.0,1600.0,30,SALES,CHICAGO
10,7521,WARD,SALESMAN,7698.0,1981-02-22,500.0,1250.0,30,SALES,CHICAGO
11,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1400.0,1250.0,30,SALES,CHICAGO
13,7844,TURNER,SALESMAN,7698.0,1981-09-08,0.0,1500.0,30,SALES,CHICAGO
14,7900,JAMES,CLERK,7698.0,1981-12-03,NaN,950.0,30,SALES,CHICAGO

In [22]:
# Only names
empdept[
    empdept['job'] != 'MANAGER'
]['ename']

0     Taheera
2        KING
3      MILLER
4       SMITH
6       SCOTT
7       ADAMS
8        FORD
9       ALLEN
10       WARD
11     MARTIN
13     TURNER
14      JAMES
Name: ename, dtype: object

In [23]:
# 4. Names of employees with specific employee numbers like 7369, 7521, 7839, 7934, 7788
empdept[
    empdept['empno'].isin([7369, 7521, 7839, 7934, 7788])
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
2,7839,KING,PRESIDENT,NaN,1981-11-17,NaN,5000.0,10,ACCOUNTING,NEW YORK
3,7934,MILLER,CLERK,7782.0,1982-01-23,NaN,1300.0,10,ACCOUNTING,NEW YORK
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
10,7521,WARD,SALESMAN,7698.0,1981-02-22,500.0,1250.0,30,SALES,CHICAGO

In [25]:
# Only name and employee numbers
empdept[
    empdept['empno'].isin([7369, 7521, 7839, 7934, 7788])
][['ename','empno']]

     ename  empno
2     KING   7839
3   MILLER   7934
4    SMITH   7369
6    SCOTT   7788
10    WARD   7521

In [26]:
# 5. Employees not in 30, 40, and 10
empdept[
    ~empdept['deptno'].isin([30, 40, 10])
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
5,7566,JONES,MANAGER,7839.0,1981-04-02,NaN,2975.0,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
7,7876,ADAMS,CLERK,7788.0,1987-05-23,NaN,1100.0,20,RESEARCH,DALLAS
8,7902,FORD,ANALYST,7566.0,1981-12-03,NaN,3000.0,20,RESEARCH,DALLAS

In [27]:
# 6. Employees joined between 30-Jun-1981 and 31-Dec-1981
empdept[
    (empdept['hiredate'] >= '1981-06-30') &
    (empdept['hiredate'] <= '1981-12-31')
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
2,7839,KING,PRESIDENT,NaN,1981-11-17,NaN,5000.0,10,ACCOUNTING,NEW YORK
8,7902,FORD,ANALYST,7566.0,1981-12-03,NaN,3000.0,20,RESEARCH,DALLAS
11,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1400.0,1250.0,30,SALES,CHICAGO
13,7844,TURNER,SALESMAN,7698.0,1981-09-08,0.0,1500.0,30,SALES,CHICAGO
14,7900,JAMES,CLERK,7698.0,1981-12-03,NaN,950.0,30,SALES,CHICAGO

In [28]:
# 7. Different designation in the company
empdept['job'].unique()

array(['ANALYST', 'MANAGER', 'PRESIDENT', 'CLERK', 'SALESMAN'],
      dtype=object)

In [29]:
# 8. Employees who are not eligible for commission
empdept[
    empdept['comm'].isnull()
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
1,7782,CLARK,MANAGER,7839.0,1981-06-09,NaN,2450.0,10,ACCOUNTING,NEW YORK
2,7839,KING,PRESIDENT,NaN,1981-11-17,NaN,5000.0,10,ACCOUNTING,NEW YORK
3,7934,MILLER,CLERK,7782.0,1982-01-23,NaN,1300.0,10,ACCOUNTING,NEW YORK
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
5,7566,JONES,MANAGER,7839.0,1981-04-02,NaN,2975.0,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
7,7876,ADAMS,CLERK,7788.0,1987-05-23,NaN,1100.0,20,RESEARCH,DALLAS
8,7902,FORD,ANALYST,7566.0,1981-12-03,NaN,3000.0,20,RESEARCH,DALLAS
12,7698,BLAKE,MANAGER,7839.0,1981-05-01,NaN,2850.0,30,SALES,CHICAGO
14,7900,JAMES,CLERK,7698.0,1981-12-03,NaN,950.0,30,SALES,CHICAGO

In [30]:
# 9. Employee who does not report to anybody
    empdept[
    empdept['mgr'].isnull()
][['ename', 'job']]

  ename        job
2  KING  PRESIDENT

In [31]:
# 10. Employees not assigned to any department
empdept[
    empdept['deptno'].isnull()
]

Empty DataFrame
Columns: [empno, ename, job, mgr, hiredate, comm, sal, deptno, dname, loc]
Index: []

In [32]:
# 11. Employees eligible for commission
empdept[
    empdept['comm'].notnull()
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
0,1234,Taheera,ANALYST,7839.0,1988-12-17,100.0,5000.0,10,ACCOUNTING,NEW YORK
9,7499,ALLEN,SALESMAN,7698.0,1981-02-20,300.0,1600.0,30,SALES,CHICAGO
10,7521,WARD,SALESMAN,7698.0,1981-02-22,500.0,1250.0,30,SALES,CHICAGO
11,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1400.0,1250.0,30,SALES,CHICAGO
13,7844,TURNER,SALESMAN,7698.0,1981-09-08,0.0,1500.0,30,SALES,CHICAGO

In [33]:
# 12. Names starting or ending with S
empdept[
    empdept['ename'].str.startswith('S') |
    empdept['ename'].str.endswith('S')
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
4,7369,SMITH,CLERK,7902.0,1980-12-17,NaN,800.0,20,RESEARCH,DALLAS
5,7566,JONES,MANAGER,7839.0,1981-04-02,NaN,2975.0,20,RESEARCH,DALLAS
6,7788,SCOTT,ANALYST,7566.0,1987-04-19,NaN,3000.0,20,RESEARCH,DALLAS
7,7876,ADAMS,CLERK,7788.0,1987-05-23,NaN,1100.0,20,RESEARCH,DALLAS
14,7900,JAMES,CLERK,7698.0,1981-12-03,NaN,950.0,30,SALES,CHICAGO

In [34]:
# 13. Names with the second character "i"
empdept[
    empdept['ename'].str[1] == 'I'
]

,empno,ename,job,mgr,hiredate,comm,sal,deptno,dname,loc
2,7839,KING,PRESIDENT,NaN,1981-11-17,NaN,5000.0,10,ACCOUNTING,NEW YORK
3,7934,MILLER,CLERK,7782.0,1982-01-23,NaN,1300.0,10,ACCOUNTING,NEW YORK

In [35]:
# 14. Number of employees
empdept['empno'].count()

np.int64(15)

In [36]:
# 15. Number of designations
empdept['empno'].count()

np.int64(15)

In [37]:
# 16. Total salaries
empdept['sal'].sum()

np.float64(34025.0)

In [38]:
# 17. Maximum, minimum, and average salary
print("Maximum Salary:", empdept['sal'].max())
print("Minimum Salary:", empdept['sal'].min())
print("Average Salary:", empdept['sal'].mean())

Maximum Salary: 5000.0
Minimum Salary: 800.0
Average Salary: 2268.3333333333335

In [39]:
# 18. The maximum salary of a salesman
empdept[
    empdept['job'] == 'SALESMAN'
]['sal'].max()

1600.0