In [1]:
pip install sqlalchemy
pip install pymysql

SyntaxError: invalid syntax (2994122548.py, line 1)

In [7]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [8]:
engine1 = create_engine(
    "mysql+pymysql://root:piit2025@localhost:3306/piit"
)
print (engine1)

Engine(mysql+pymysql://root:***@localhost:3306/piit)

In [9]:
# Function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [12]:
q("SHOW DATABASES")

             Database
0             college
1          healthcare
2  information_schema
3          my_project
4               mysql
5  performance_schema
6                piit
7               sales
8                 sys

In [13]:
q("SHOW TABLES")

  Tables_in_piit
0           dept
1            emp
2       students

In [14]:
q("SELECT * FROM emp")

    empno    ename        job     mgr    hiredate     sal    comm  deptno
0    1234  Taheera    ANALYST  7839.0  1988-12-17  5000.0   100.0      10
1    7369    SMITH      CLERK  7902.0  1980-12-17   800.0     NaN      20
2    7499    ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0      30
3    7521     WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0      30
4    7566    JONES    MANAGER  7839.0  1981-04-02  2975.0     NaN      20
5    7654   MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0      30
6    7698    BLAKE    MANAGER  7839.0  1981-05-01  2850.0     NaN      30
7    7782    CLARK    MANAGER  7839.0  1981-06-09  2450.0     NaN      10
8    7788    SCOTT    ANALYST  7566.0  1987-04-19  3000.0     NaN      20
9    7839     KING  PRESIDENT     NaN  1981-11-17  5000.0     NaN      10
10   7844   TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0      30
11   7876    ADAMS      CLERK  7788.0  1987-05-23  1100.0     NaN      20
12   7900    JAMES      CLERK  7698.0  1981-12-03   950.0     NaN      30
13   7902     FORD    ANALYST  7566.0  1981-12-03  3000.0     NaN      20
14   7934   MILLER      CLERK  7782.0  1982-01-23  1300.0     NaN      10

In [15]:
# Count total employees
q("SELECT COUNT(*) FROM emp")

   COUNT(*)
0        15

In [17]:
q("SELECT COUNT(*) AS total_emp FROM emp")

   total_emp
0         15

In [19]:
# Show employees by department
q("SELECT deptno, COUNT(*) AS total_emp FROM emp GROUP BY deptno")

   deptno  total_emp
0      10          4
1      20          5
2      30          6

In [24]:
# Highest paying employee
q("""SELECT * 
    FROM emp 
        ORDER BY sal DESC 
            LIMIT 1""")

   empno    ename      job   mgr    hiredate     sal   comm  deptno
0   1234  Taheera  ANALYST  7839  1988-12-17  5000.0  100.0      10

In [25]:
# Top five highest paying employees
q("SELECT * FROM emp ORDER BY sal DESC LIMIT 5")

   empno    ename        job     mgr    hiredate     sal   comm  deptno
0   1234  Taheera    ANALYST  7839.0  1988-12-17  5000.0  100.0      10
1   7839     KING  PRESIDENT     NaN  1981-11-17  5000.0    NaN      10
2   7788    SCOTT    ANALYST  7566.0  1987-04-19  3000.0    NaN      20
3   7902     FORD    ANALYST  7566.0  1981-12-03  3000.0    NaN      20
4   7566    JONES    MANAGER  7839.0  1981-04-02  2975.0    NaN      20

In [26]:
# Lowest paying employee
q("SELECT * FROM emp ORDER BY sal ASC limit 1")

   empno  ename    job   mgr    hiredate    sal  comm  deptno
0   7369  SMITH  CLERK  7902  1980-12-17  800.0  None      20

In [28]:
# Lowest five paying employees
q("SELECT * FROM emp ORDER BY sal ASC LIMIT 5")

   empno   ename       job   mgr    hiredate     sal    comm  deptno
0   7369   SMITH     CLERK  7902  1980-12-17   800.0     NaN      20
1   7900   JAMES     CLERK  7698  1981-12-03   950.0     NaN      30
2   7876   ADAMS     CLERK  7788  1987-05-23  1100.0     NaN      20
3   7521    WARD  SALESMAN  7698  1981-02-22  1250.0   500.0      30
4   7654  MARTIN  SALESMAN  7698  1981-09-28  1250.0  1400.0      30

In [29]:
# Average salary by department
q("SELECT deptno, AVG(SAL) AS avg_salary FROM emp GROUP BY deptno")

   deptno   avg_salary
0      10  3437.500000
1      20  2175.000000
2      30  1566.666667

In [32]:
# Employees getting commission
q("""SELECT ename, sal, comm
    FROM emp 
        WHERE comm IS NOT NULL""")

     ename     sal    comm
0  Taheera  5000.0   100.0
1    ALLEN  1600.0   300.0
2     WARD  1250.0   500.0
3   MARTIN  1250.0  1400.0
4   TURNER  1500.0     0.0

In [33]:
# Employees aren't getting commission
q("SELECT ename, sal, comm FROM emp WHERE comm IS NULL")

    ename     sal  comm
0   SMITH   800.0  None
1   JONES  2975.0  None
2   BLAKE  2850.0  None
3   CLARK  2450.0  None
4   SCOTT  3000.0  None
5    KING  5000.0  None
6   ADAMS  1100.0  None
7   JAMES   950.0  None
8    FORD  3000.0  None
9  MILLER  1300.0  None

In [35]:
# Job-wise employee count
q("SELECT job, COUNT(*) AS total_emp FROM emp GROUP BY job")

         job  total_emp
0    ANALYST          3
1      CLERK          4
2   SALESMAN          4
3    MANAGER          3
4  PRESIDENT          1

In [42]:
# employee getting more than average salary
q("""SELECT ename, job, sal 
    FROM emp 
        WHERE sal > (SELECT AVG(sal) FROM emp)""")

     ename        job     sal
0  Taheera    ANALYST  5000.0
1    JONES    MANAGER  2975.0
2    BLAKE    MANAGER  2850.0
3    CLARK    MANAGER  2450.0
4    SCOTT    ANALYST  3000.0
5     KING  PRESIDENT  5000.0
6     FORD    ANALYST  3000.0

In [43]:
# Department-wise salary report
q("""SELECT deptno,
  COUNT(*) AS total_emp,
  SUM(sal) AS total_salary,
  AVG(sal) AS avg_salary,
  MAX(sal) AS max_salary,
  MIN(sal) AS min_salary
  FROM emp
  GROUP BY deptno""")

   deptno  total_emp  total_salary   avg_salary  max_salary  min_salary
0      10          4       13750.0  3437.500000      5000.0      1300.0
1      20          5       10875.0  2175.000000      3000.0       800.0
2      30          6        9400.0  1566.666667      2850.0       950.0