In [1]:
# pip install sqlalchemy pymysql

In [2]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [7]:
engine1 = create_engine(
    "mysql+pymysql://root:piit2025@localhost:3306/highschool"
)
print (engine1)

Engine(mysql+pymysql://root:***@localhost:3306/highschool)

In [4]:
# Function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [5]:
q("SHOW DATABASES")

             Database
0             college
1          healthcare
2          highschool
3  information_schema
4          my_project
5               mysql
6  performance_schema
7                piit
8               sales
9                 sys

In [8]:
q("SHOW TABLES")

  Tables_in_highschool
0           highschool
1             students

In [9]:
q("SELECT * FROM highschool")

,student_id,student_name,gender,grade,age,attendance_pct,math_score,science_score,english_score,study_hours,extracurricular,parent_education,internet_access,graduation_status
0,1001,John Smith,Male,9,14,92,88,84,79,3.5,Yes,Bachelor,Yes,Active
1,1002,Emma Johnson,Female,10,15,96,91,89,94,4.2,Yes,Master,Yes,Active
2,1003,Liam Brown,Male,11,16,85,72,75,70,2.0,No,High School,Yes,Active
3,1004,Olivia Davis,Female,12,17,98,95,97,96,5.0,Yes,PhD,Yes,Graduated
4,1005,Noah Wilson,Male,9,14,78,65,68,62,1.5,No,High School,No,Active
5,1006,Ava Martinez,Female,10,15,89,81,83,85,3.0,Yes,Bachelor,Yes,Active
6,1007,William Anderson,Male,11,16,94,90,88,86,4.1,Yes,Master,Yes,Active
7,1008,Sophia Taylor,Female,12,17,97,93,95,98,5.2,Yes,Bachelor,Yes,Graduated
8,1009,James Thomas,Male,10,15,82,74,71,73,2.3,No,Associate,Yes,Active
9,1010,Isabella Moore,Female,11,16,91,87,84,89,3.8,Yes,Master,Yes,Active
10,1011,Benjamin Jackson,Male,12,17,88,79,82,77,2.9,Yes,High School,Yes,Graduated
11,1012,Mia White,Female,9,14,95,92,90,91,4.5,Yes,Bachelor,Yes,Active
12,1013,Lucas Harris,Male,10,15,76,60,64,58,1.2,No,High School,No,Active
13,1014,Charlotte Martin,Female,11,16,99,98,97,99,6.0,Yes,PhD,Yes,Active
14,1015,Henry Thompson,Male,12,17,84,73,70,75,2.4,No,Associate,Yes,Graduated

In [10]:
# Average math score
q("SELECT AVG(math_score) AS avg_math FROM highschool")

   avg_math
0   82.5333

In [11]:
# Highest math-scoring student
q("""SELECT student_name, math_score
    FROM highschool
    ORDER BY math_score DESC
    LIMIT 1""")

       student_name  math_score
0  Charlotte Martin          98

In [12]:
# Top 5 math-scoring student
q("""SELECT student_name, gender, grade, age, math_score
    FROM highschool
    ORDER BY math_score DESC
    LIMIT 5""")

       student_name  gender  grade  age  math_score
0  Charlotte Martin  Female     11   16          98
1      Olivia Davis  Female     12   17          95
2     Sophia Taylor  Female     12   17          93
3         Mia White  Female      9   14          92
4      Emma Johnson  Female     10   15          91

In [13]:
# Attendance analysis
q("""SELECT student_name, gender, grade, age, attendance_pct
    FROM highschool
    ORDER BY attendance_pct DESC""")

        student_name  gender  grade  age  attendance_pct
0   Charlotte Martin  Female     11   16              99
1       Olivia Davis  Female     12   17              98
2      Sophia Taylor  Female     12   17              97
3       Emma Johnson  Female     10   15              96
4          Mia White  Female      9   14              95
5   William Anderson    Male     11   16              94
6         John Smith    Male      9   14              92
7     Isabella Moore  Female     11   16              91
8       Ava Martinez  Female     10   15              89
9   Benjamin Jackson    Male     12   17              88
10        Liam Brown    Male     11   16              85
11    Henry Thompson    Male     12   17              84
12      James Thomas    Male     10   15              82
13       Noah Wilson    Male      9   14              78
14      Lucas Harris    Male     10   15              76

In [16]:
# Average score by gender
q("""SELECT gender,
    AVG(math_score) AS avg_math,
    AVG(science_score) AS avg_science,
    AVG(english_score) AS avg_english
    FROM highschool
    GROUP BY gender""")

   gender  avg_math  avg_science  avg_english
0    Male    75.125      75.2500      72.5000
1  Female    91.000      90.7143      93.1429

In [17]:
# Students with low attendance
q("""SELECT student_name, attendance_pct
    FROM highschool
    WHERE attendance_pct <80""")

   student_name  attendance_pct
0   Noah Wilson              78
1  Lucas Harris              76

In [19]:
# Students with more than 90 in math
q("""SELECT student_id, student_name, math_score, science_score, english_score
    FROM highschool
    WHERE math_score > 90""")

   student_id      student_name  math_score  science_score  english_score
0        1002      Emma Johnson          91             89             94
1        1004      Olivia Davis          95             97             96
2        1008     Sophia Taylor          93             95             98
3        1012         Mia White          92             90             91
4        1014  Charlotte Martin          98             97             99

In [21]:
# Students with more than 88 in English
q("""SELECT student_name, english_score, math_score, science_score
    FROM highschool
    WHERE english_score > 88""")

       student_name  english_score  math_score  science_score
0      Emma Johnson             94          91             89
1      Olivia Davis             96          95             97
2     Sophia Taylor             98          93             95
3    Isabella Moore             89          87             84
4         Mia White             91          92             90
5  Charlotte Martin             99          98             97

In [22]:
# Students with more than 88 in English in descending order
q("""SELECT student_name, english_score, math_score, science_score
    FROM highschool
    WHERE english_score > 88
    ORDER BY english_score DESC""")

       student_name  english_score  math_score  science_score
0  Charlotte Martin             99          98             97
1     Sophia Taylor             98          93             95
2      Olivia Davis             96          95             97
3      Emma Johnson             94          91             89
4         Mia White             91          92             90
5    Isabella Moore             89          87             84

In [25]:
# Graduation status report
q("""SELECT graduation_status,
    COUNT(*) AS total_students
    FROM highschool
    GROUP BY graduation_status""")

  graduation_status  total_students
0            Active              11
1         Graduated               4

In [26]:
# Top 5 students on overall scores
q("""SELECT student_name,
    (math_score + science_score + english_score) AS total_score
    FROM highschool
    ORDER BY total_score DESC
    LIMIT 5""")

       student_name  total_score
0  Charlotte Martin          294
1      Olivia Davis          288
2     Sophia Taylor          286
3      Emma Johnson          274
4         Mia White          273