In [1]:
import pandas as pd

In [2]:
from pydataset import data
mtcars = data('mtcars')
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [3]:
mtcars['am'] = mtcars['am'].map({0:'auto', 1:'manual'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,auto,3,2

In [5]:
mtcars['vs'] = mtcars['vs'].map({0:'vshaped', 1:'straight'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,vshaped,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,vshaped,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,straight,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,straight,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,vshaped,auto,3,2

In [6]:
mtcars['mpg'].max()

33.9

In [7]:
mtcars['mpg'].min()

10.4

In [8]:
mtcars['vs'] = mtcars['vs'].map({1:'vshaped', 2:'straight'})
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,NaN,manual,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,NaN,manual,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,NaN,manual,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,NaN,auto,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,NaN,auto,3,2

In [9]:
mtcars.pivot_table(values = 'mpg', index='gear', observed=False)

            mpg
gear
3     16.106667
4     24.533333
5     21.380000

In [10]:
mtcars.pivot_table(values = 'hp', index='cyl', observed=False)

             hp
cyl
4     82.636364
6    122.285714
8    209.214286

In [12]:
mtcars.pivot_table(values = ['mpg','hp'], index=['gear','am'], observed=True, 
                   aggfunc=['sum','mean','count']).reset_index()

  gear      am   sum               mean            count
                  hp    mpg          hp        mpg    hp mpg
0    3    auto  2642  241.6  176.133333  16.106667    15  15
1    4    auto   403   84.2  100.750000  21.050000     4   4
2    4  manual   671  210.2   83.875000  26.275000     8   8
3    5  manual   978  106.9  195.600000  21.380000     5   5

In [13]:
data = [
    [1, 'Taheera', 70, 86],
    [2, 'Aelita', 56, 90],
    [3, 'Khulan', 87, 90],
    [4, 'Batgerel', 71, 79],
    [5, 'Manisha', 88, 76],
]

df = pd.DataFrame(data, columns=['Rollno','Name', 'Maths', 'English'])

In [14]:
df

   Rollno      Name  Maths  English
0       1   Taheera     70       86
1       2    Aelita     56       90
2       3    Khulan     87       90
3       4  Batgerel     71       79
4       5   Manisha     88       76

wide to long

In [15]:
df_long = df.melt(id_vars=['Rollno','Name'], 
                 value_vars=['Maths','English'], 
                 var_name='Subject', 
                 value_name='Marks')
df_long

   Rollno      Name  Subject  Marks
0       1   Taheera    Maths     70
1       2    Aelita    Maths     56
2       3    Khulan    Maths     87
3       4  Batgerel    Maths     71
4       5   Manisha    Maths     88
5       1   Taheera  English     86
6       2    Aelita  English     90
7       3    Khulan  English     90
8       4  Batgerel  English     79
9       5   Manisha  English     76

In [16]:
wide_df = df_long.pivot(index=['Rollno','Name'], columns='Subject',
             values='Marks').reset_index(drop=False).rename_axis(None, axis=1)
wide_df

   Rollno      Name  English  Maths
0       1   Taheera       86     70
1       2    Aelita       90     56
2       3    Khulan       90     87
3       4  Batgerel       79     71
4       5   Manisha       76     88

In [17]:
from pydataset import data
import pandas as pd

aq = data('airquality')
aq.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5

In [18]:
aq.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5