In [2]:
# pip install sqlalchemy pymysql

In [3]:
from sqlalchemy import create_engine, text
import pymysql
import pandas as pd
import os

In [4]:
engine1 = create_engine(
    "mysql+pymysql://root:piit2025@localhost:3306/patientcare"
)
print (engine1)

Engine(mysql+pymysql://root:***@localhost:3306/patientcare)

In [5]:
# Function to run the query with parameters or query
def q(sql, **params):
    with engine1.connect() as conn:
        return pd.read_sql(text(sql), conn, params=params)

In [6]:
q("SHOW TABLES")

  Tables_in_patientcare
0              patients

In [7]:
q("SELECT * FROM patients LIMIT 30")

,Patient_ID,Age,Gender,Disease,Blood_Pressure,Cholesterol,Treatment_Cost,Hospital_Days,Outcome,Smoking_Status
0,P00001,64,Female,Diabetes,125/74,249,8664,2,Critical,Smoker
1,P00002,87,Female,Hypertension,137/98,243,4641,3,Under Treatment,Smoker
2,P00003,74,Female,Heart Disease,121/87,207,16405,12,Critical,Smoker
3,P00004,38,Female,Heart Disease,120/98,205,18612,13,Under Treatment,Non-Smoker
4,P00005,42,Female,Diabetes,151/85,172,4160,7,Critical,Smoker
5,P00006,80,Female,Asthma,161/102,204,4789,3,Recovered,Non-Smoker
6,P00007,57,Male,Flu,164/79,212,2365,1,Critical,Non-Smoker
7,P00008,54,Male,Diabetes,144/98,255,3694,7,Recovered,Non-Smoker
8,P00009,84,Male,Diabetes,168/89,190,8295,4,Under Treatment,Smoker
9,P00010,40,Female,Hypertension,115/77,166,4492,7,Critical,Smoker
10,P00011,74,Female,Asthma,120/76,225,2613,3,Under Treatment,Non-Smoker
11,P00012,37,Male,Heart Disease,118/81,195,16240,10,Recovered,Smoker
12,P00013,57,Female,Heart Disease,127/84,190,11685,10,Recovered,Non-Smoker
13,P00014,27,Male,Heart Disease,162/72,242,17374,15,Recovered,Non-Smoker
14,P00015,50,Female,Asthma,139/78,193,1624,1,Recovered,Smoker
15,P00016,49,Female,Diabetes,157/84,197,6043,6,Under Treatment,Non-Smoker
16,P00017,73,Male,Asthma,161/80,219,3990,3,Recovered,Non-Smoker
17,P00018,27,Male,Heart Disease,126/101,202,19631,8,Critical,Non-Smoker
18,P00019,48,Female,Hypertension,120/71,239,3018,5,Under Treatment,Non-Smoker
19,P00020,50,Female,Diabetes,166/103,216,3533,3,Recovered,Smoker
20,P00021,24,Male,Flu,147/102,289,2321,1,Under Treatment,Non-Smoker
21,P00022,42,Female,Asthma,158/95,296,3090,4,Critical,Non-Smoker
22,P00023,27,Male,Flu,110/85,209,1160,2,Critical,Non-Smoker
23,P00024,27,Female,Diabetes,131/88,181,4016,6,Critical,Smoker
24,P00025,53,Male,Diabetes,170/86,172,4787,8,Critical,Non-Smoker
25,P00026,70,Female,Hypertension,140/83,258,7728,3,Critical,Non-Smoker
26,P00027,26,Female,Hypertension,147/105,168,5626,4,Recovered,Smoker
27,P00028,71,Female,Hypertension,156/77,270,7825,7,Critical,Non-Smoker
28,P00029,62,Female,Diabetes,114/88,221,7108,7,Recovered,Smoker
29,P00030,55,Male,Heart Disease,155/92,213,14690,7,Critical,Non-Smoker

In [8]:
# Overall patient analysis
q("""SELECT  
    COUNT(*) AS total_patients,
    AVG(age) AS avg_age,
    MIN(AGE) AS younger_patient,
    MAX(AGE) AS oldest_patient
    FROM patients""")

   total_patients  avg_age  younger_patient  oldest_patient
0            5000  53.8414               18              90

In [9]:
# Gender distribution
q("SELECT gender, COUNT(*) AS total_patients FROM patients GROUP BY gender")

   gender  total_patients
0  Female            2554
1    Male            2446

In [18]:
q = """
SELECT
    CASE
        WHEN age < 18 THEN 'Child'
        WHEN age BETWEEN 18 AND 39 THEN 'Young Adult'
        WHEN age BETWEEN 40 AND 59 THEN 'Middle Age'
        ELSE 'Senior'
    END AS age_group,
    COUNT(*) AS total_patients
FROM patients
GROUP BY age_group
ORDER BY total_patients DESC;
"""
pd.read_sql(q, engine1)

     age_group  total_patients
0       Senior            2090
1  Young Adult            1508
2   Middle Age            1402

In [30]:
# Upper
q("""
SELECT
    Patient_ID,
    UPPER(Disease) AS disease_upper
FROM patients
LIMIT 20;
""")

   Patient_ID  disease_upper
0      P00001       DIABETES
1      P00002   HYPERTENSION
2      P00003  HEART DISEASE
3      P00004  HEART DISEASE
4      P00005       DIABETES
5      P00006         ASTHMA
6      P00007            FLU
7      P00008       DIABETES
8      P00009       DIABETES
9      P00010   HYPERTENSION
10     P00011         ASTHMA
11     P00012  HEART DISEASE
12     P00013  HEART DISEASE
13     P00014  HEART DISEASE
14     P00015         ASTHMA
15     P00016       DIABETES
16     P00017         ASTHMA
17     P00018  HEART DISEASE
18     P00019   HYPERTENSION
19     P00020       DIABETES

In [31]:
# Upper
q("""
SELECT
    Patient_ID,
    UPPER(Disease) AS disease_upper
FROM patients
LIMIT 10;
""")

  Patient_ID  disease_upper
0     P00001       DIABETES
1     P00002   HYPERTENSION
2     P00003  HEART DISEASE
3     P00004  HEART DISEASE
4     P00005       DIABETES
5     P00006         ASTHMA
6     P00007            FLU
7     P00008       DIABETES
8     P00009       DIABETES
9     P00010   HYPERTENSION

In [32]:
# Lower
q("""
SELECT
    Patient_ID,
    LOWER(Outcome) AS outcome_lower
FROM patients
LIMIT 20;
""")

   Patient_ID    outcome_lower
0      P00001         critical
1      P00002  under treatment
2      P00003         critical
3      P00004  under treatment
4      P00005         critical
5      P00006        recovered
6      P00007         critical
7      P00008        recovered
8      P00009  under treatment
9      P00010         critical
10     P00011  under treatment
11     P00012        recovered
12     P00013        recovered
13     P00014        recovered
14     P00015        recovered
15     P00016  under treatment
16     P00017        recovered
17     P00018         critical
18     P00019  under treatment
19     P00020        recovered

In [33]:
# Concatenate
q("""
SELECT
    Patient_ID,
    CONCAT(Disease, ' - ', Outcome) AS patient_status
FROM patients
LIMIT 20;
""")

   Patient_ID                   patient_status
0      P00001              Diabetes - Critical
1      P00002   Hypertension - Under Treatment
2      P00003         Heart Disease - Critical
3      P00004  Heart Disease - Under Treatment
4      P00005              Diabetes - Critical
5      P00006               Asthma - Recovered
6      P00007                   Flu - Critical
7      P00008             Diabetes - Recovered
8      P00009       Diabetes - Under Treatment
9      P00010          Hypertension - Critical
10     P00011         Asthma - Under Treatment
11     P00012        Heart Disease - Recovered
12     P00013        Heart Disease - Recovered
13     P00014        Heart Disease - Recovered
14     P00015               Asthma - Recovered
15     P00016       Diabetes - Under Treatment
16     P00017               Asthma - Recovered
17     P00018         Heart Disease - Critical
18     P00019   Hypertension - Under Treatment
19     P00020             Diabetes - Recovered

In [34]:
# Length
q("""
SELECT
    Disease,
    LENGTH(Disease) AS disease_length
FROM patients
LIMIT 20;
""")

          Disease  disease_length
0        Diabetes               8
1    Hypertension              12
2   Heart Disease              13
3   Heart Disease              13
4        Diabetes               8
5          Asthma               6
6             Flu               3
7        Diabetes               8
8        Diabetes               8
9    Hypertension              12
10         Asthma               6
11  Heart Disease              13
12  Heart Disease              13
13  Heart Disease              13
14         Asthma               6
15       Diabetes               8
16         Asthma               6
17  Heart Disease              13
18   Hypertension              12
19       Diabetes               8

In [35]:
# Left
q("""
SELECT
    Disease,
    LEFT(Disease, 5) AS first_five
FROM patients
LIMIT 20;
""")

          Disease first_five
0        Diabetes      Diabe
1    Hypertension      Hyper
2   Heart Disease      Heart
3   Heart Disease      Heart
4        Diabetes      Diabe
5          Asthma      Asthm
6             Flu        Flu
7        Diabetes      Diabe
8        Diabetes      Diabe
9    Hypertension      Hyper
10         Asthma      Asthm
11  Heart Disease      Heart
12  Heart Disease      Heart
13  Heart Disease      Heart
14         Asthma      Asthm
15       Diabetes      Diabe
16         Asthma      Asthm
17  Heart Disease      Heart
18   Hypertension      Hyper
19       Diabetes      Diabe

In [38]:
# Right
q("""
SELECT
    Disease,
    RIGHT(Disease, 6) AS last_six
FROM patients
LIMIT 20;
""")

          Disease last_six
0        Diabetes   abetes
1    Hypertension   ension
2   Heart Disease   isease
3   Heart Disease   isease
4        Diabetes   abetes
5          Asthma   Asthma
6             Flu      Flu
7        Diabetes   abetes
8        Diabetes   abetes
9    Hypertension   ension
10         Asthma   Asthma
11  Heart Disease   isease
12  Heart Disease   isease
13  Heart Disease   isease
14         Asthma   Asthma
15       Diabetes   abetes
16         Asthma   Asthma
17  Heart Disease   isease
18   Hypertension   ension
19       Diabetes   abetes

In [39]:
# All six string functions
q("""
SELECT
    Patient_ID,
    UPPER(Disease) AS disease_upper,
    LOWER(Outcome) AS outcome_lower,
    CONCAT(Disease, ' - ', Outcome) AS patient_status,
    LENGTH(Disease) AS disease_length,
    LEFT(Disease, 3) AS first_three,
    RIGHT(Disease, 3) AS last_three
FROM patients
LIMIT 20;
""")

,Patient_ID,disease_upper,outcome_lower,patient_status,disease_length,first_three,last_three
0,P00001,DIABETES,critical,Diabetes - Critical,8,Dia,tes
1,P00002,HYPERTENSION,under treatment,Hypertension - Under Treatment,12,Hyp,ion
2,P00003,HEART DISEASE,critical,Heart Disease - Critical,13,Hea,ase
3,P00004,HEART DISEASE,under treatment,Heart Disease - Under Treatment,13,Hea,ase
4,P00005,DIABETES,critical,Diabetes - Critical,8,Dia,tes
5,P00006,ASTHMA,recovered,Asthma - Recovered,6,Ast,hma
6,P00007,FLU,critical,Flu - Critical,3,Flu,Flu
7,P00008,DIABETES,recovered,Diabetes - Recovered,8,Dia,tes
8,P00009,DIABETES,under treatment,Diabetes - Under Treatment,8,Dia,tes
9,P00010,HYPERTENSION,critical,Hypertension - Critical,12,Hyp,ion
10,P00011,ASTHMA,under treatment,Asthma - Under Treatment,6,Ast,hma
11,P00012,HEART DISEASE,recovered,Heart Disease - Recovered,13,Hea,ase
12,P00013,HEART DISEASE,recovered,Heart Disease - Recovered,13,Hea,ase
13,P00014,HEART DISEASE,recovered,Heart Disease - Recovered,13,Hea,ase
14,P00015,ASTHMA,recovered,Asthma - Recovered,6,Ast,hma
15,P00016,DIABETES,under treatment,Diabetes - Under Treatment,8,Dia,tes
16,P00017,ASTHMA,recovered,Asthma - Recovered,6,Ast,hma
17,P00018,HEART DISEASE,critical,Heart Disease - Critical,13,Hea,ase
18,P00019,HYPERTENSION,under treatment,Hypertension - Under Treatment,12,Hyp,ion
19,P00020,DIABETES,recovered,Diabetes - Recovered,8,Dia,tes

In [40]:
# Format (useful for cost)
q("""SELECT
    Treatment_Cost,
    FORMAT(Treatment_Cost, 2) AS formatted_cost
FROM patients;""")

      Treatment_Cost formatted_cost
0               8664       8,664.00
1               4641       4,641.00
2              16405      16,405.00
3              18612      18,612.00
4               4160       4,160.00
...              ...            ...
4995            2911       2,911.00
4996             703         703.00
4997            6941       6,941.00
4998            2158       2,158.00
4999            4254       4,254.00

[5000 rows x 2 columns]

In [41]:
q("""SELECT
    Treatment_Cost,
    FORMAT(Treatment_Cost, 2) AS formatted_cost
FROM patients
LIMIT 10;""")

   Treatment_Cost formatted_cost
0            8664       8,664.00
1            4641       4,641.00
2           16405      16,405.00
3           18612      18,612.00
4            4160       4,160.00
5            4789       4,789.00
6            2365       2,365.00
7            3694       3,694.00
8            8295       8,295.00
9            4492       4,492.00

In [42]:
# Concatenate with a separator
q("""SELECT
    Patient_ID,
    CONCAT_WS(' | ', Disease, Outcome, Smoking_Status)
    AS patient_summary
FROM patients
LIMIT 10;""")

  Patient_ID                               patient_summary
0     P00001                  Diabetes | Critical | Smoker
1     P00002       Hypertension | Under Treatment | Smoker
2     P00003             Heart Disease | Critical | Smoker
3     P00004  Heart Disease | Under Treatment | Non-Smoker
4     P00005                  Diabetes | Critical | Smoker
5     P00006               Asthma | Recovered | Non-Smoker
6     P00007                   Flu | Critical | Non-Smoker
7     P00008             Diabetes | Recovered | Non-Smoker
8     P00009           Diabetes | Under Treatment | Smoker
9     P00010              Hypertension | Critical | Smoker

In [43]:
# LPAD (add character to the left)
q("""SELECT
    Patient_ID,
    LPAD(Age, 3, '0') AS age_code
FROM patients
LIMIT 5;""")

  Patient_ID age_code
0     P00001      064
1     P00002      087
2     P00003      074
3     P00004      038
4     P00005      042

In [44]:
# RPAD (add character to the right)
q("""SELECT
    RPAD(Disease, 15, '*') AS disease_format
FROM patients
LIMIT 5;""")

    disease_format
0  Diabetes*******
1  Hypertension***
2  Heart Disease**
3  Heart Disease**
4  Diabetes*******

In [45]:
q("""SELECT
    Patient_ID,
    RPAD(Disease, 15, '*') AS disease_format
FROM patients
LIMIT 5;""")

  Patient_ID   disease_format
0     P00001  Diabetes*******
1     P00002  Hypertension***
2     P00003  Heart Disease**
3     P00004  Heart Disease**
4     P00005  Diabetes*******