In [1]:
import pandas as pd
from pydataset import data

In [2]:
df = data('mtcars')

In [6]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

# 4.1 Add Two Columns

In [9]:
# Create a new column mpg_hp_sum = mpg + hp using a lambda function
df['mpg_hp_sum'] = df.apply(lambda x: x['mpg'] + x['hp'], axis=1)

In [10]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7

# 4.2 Conditional Label

In [16]:
# Create a new column mpg_label: • "High" if mpg > 20 • "Low" otherwise
# Use apply() with a lambda.
df['mpg_label'] = df['mpg'].apply(lambda x: 'High'if x >20 else 'Low')

In [17]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low

# 4.3 Multiply Column Values

In [18]:
# Double all hp values using map() with a lambda
df['hp_double'] = df['hp'].map(lambda x: x*2)

In [19]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,mpg_hp_sum,mpg_label,hp_double
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,131.0,High,220
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,131.0,High,220
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,115.8,High,186
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,131.4,High,220
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,193.7,Low,350

# 4.4 Filter Rows

In [20]:
# Get a list of all mpg values greater than 25 using filter() with a lambda
high_mpg = list(filter(lambda x: x >25, df['mpg']))

In [21]:
high_mpg

[32.4, 30.4, 33.9, 27.3, 26.0, 30.4]

# 4.5 Reduce to Total

In [22]:
from functools import reduce

In [23]:
# Use reduce() with a lambda to sum all cyl values in the dataset
total_cyl = reduce(lambda x, y: x + y, df['cyl'])

In [24]:
total_cyl

198

# 4.6 Sort by Custom Rule

In [25]:
# Sort the dataset by the reverse of the car names’ length using sorted() with a lambda on the index
sorted_cars = sorted(df.index, key=lambda x: len(x), reverse=True)

In [26]:
sorted_cars

['Lincoln Continental',
 'Cadillac Fleetwood',
 'Hornet Sportabout',
 'Chrysler Imperial',
 'Dodge Challenger',
 'Pontiac Firebird',
 'Hornet 4 Drive',
 'Toyota Corolla',
 'Ford Pantera L',
 'Mazda RX4 Wag',
 'Toyota Corona',
 'Porsche 914-2',
 'Maserati Bora',
 'Lotus Europa',
 'Ferrari Dino',
 'Merc 450SLC',
 'Honda Civic',
 'AMC Javelin',
 'Datsun 710',
 'Duster 360',
 'Merc 450SE',
 'Merc 450SL',
 'Camaro Z28',
 'Volvo 142E',
 'Mazda RX4',
 'Merc 240D',
 'Merc 280C',
 'Fiat X1-9',
 'Merc 230',
 'Merc 280',
 'Fiat 128',
 'Valiant']

# 4.7 Multi-Column Condition

In [3]:
import pandas as pd
from pydataset import data

In [4]:
df = data('mtcars')

In [5]:
# Create a column efficient_power = "Yes" if mpg > 20 and hp > 100, else "No"
df['efficient_power'] = df.apply(
    lambda x: 'Yes' if x['mpg'] > 20 and x['hp'] > 100 else 'No',
    axis=1
)

In [6]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,efficient_power
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Yes
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Yes
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,No
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Yes
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,No

# 4.8 Normalize a Column

In [7]:
# Normalize mpg between 0 and 1 using a lambda inside apply():
# {normalized} = (x - min)/(max - min)
df['mpg_normalized'] = df['mpg'].apply(
    lambda x: (x - df['mpg'].min()) / (df['mpg'].max() - df['mpg'].min())
)

In [8]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,efficient_power,mpg_normalized
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Yes,0.451064
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Yes,0.451064
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,No,0.527660
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Yes,0.468085
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,No,0.353191

# 4.9 Extract First Word

In [9]:
# Extract the first word from each car name (index) into a new column car_make using map() with a lambda
df['car_make'] = df.index.map(lambda x: x.split()[0])
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,efficient_power,mpg_normalized,car_make
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Yes,0.451064,Mazda
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Yes,0.451064,Mazda
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,No,0.527660,Datsun
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Yes,0.468085,Hornet
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,No,0.353191,Hornet

# 4.10 Square and Add

# Create a column hp_mpg_calc = (hp² + mpg²) using apply() with a lambda
df['hp_mpg_calc'] = df.apply(lambda x: x['hp']**2 + x['mpg']**2, axis=1)

In [20]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,efficient_power,mpg_normalized,car_make,hp_mpg_calc
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4,Yes,0.451064,Mazda,12541.00
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4,Yes,0.451064,Mazda,12541.00
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1,No,0.527660,Datsun,9168.84
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1,Yes,0.468085,Hornet,12557.96
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2,No,0.353191,Hornet,30974.69

# 4.11 Filter by Col values

In [11]:
# Filter cars with mpg > 25
high_mpg_cars = df[df['mpg'] > 25]
high_mpg_cars

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,efficient_power,mpg_normalized,car_make,hp_mpg_calc
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1,No,0.936170,Fiat,5405.76
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2,No,0.851064,Honda,3628.16
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1,No,1.000000,Toyota,5374.21
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1,No,0.719149,Fiat,5101.29
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2,No,0.663830,Porsche,8957.00
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2,Yes,0.851064,Lotus,13693.16

# 4.12 Filter and soted carnames by horsepower

In [13]:
# From above, return a list of car names sorted by horsepower
sorted_names = high_mpg_cars.sort_values('hp').index.tolist()
sorted_names

['Honda Civic',
 'Toyota Corolla',
 'Fiat 128',
 'Fiat X1-9',
 'Porsche 914-2',
 'Lotus Europa']

In [17]:
# car names and hp column together
high_mpg_cars.sort_values('hp')[['hp']]

                 hp
Honda Civic      52
Toyota Corolla   65
Fiat 128         66
Fiat X1-9        66
Porsche 914-2    91
Lotus Europa    113

In [19]:
high_mpg_cars.sort_values('hp')[['hp', 'cyl']]

                 hp  cyl
Honda Civic      52    4
Toyota Corolla   65    4
Fiat 128         66    4
Fiat X1-9        66    4
Porsche 914-2    91    4
Lotus Europa    113    4