# String in Python
- a sequence of characters used to represent text
- immutable

In [1]:
srting1='Taheera'
print(srting1)

Taheera

In [2]:
string1 = 'Tasneem'
print(string1)

Tasneem

#creating string

In [3]:
s1= "Hello"
s2= 'World'
s3= """This is a multiline string"""
print(s1)
print(s2)
print(s3)

Hello
World
This is a multiline string

In [4]:
ms = '''In Python, a string is a sequence of characters used to represent text 
GeeksforGeeks
GeeksforGeeks
 +1
. Strings are one of the most fundamental and frequently used data types in the language'''
print(ms)

In Python, a string is a sequence of characters used to represent text
GeeksforGeeks
GeeksforGeeks
 +1
. Strings are one of the most fundamental and frequently used data types in the language

# String concatenation

In [5]:
print("\n2. Concatenation")
full = s1 + " " + s2
print("Concatenated:", full)

2. Concatenation
Concatenated: Hello World

In [6]:
sc ='Aelita' + '....' + "Khulan"
print(sc)

Aelita....Khulan

In [7]:
# 3. String Repetition
# -------------------------------
print("\t\t3. Repetition")
repeat = "Hi .  How are you! " * 5
print(repeat, end=' : I have reached end of string')

		3. Repetition
Hi .  How are you! Hi .  How are you! Hi .  How are you! Hi .  How are you! Hi .  How are you!  : I have reached end of string

 4. Indexing (Access characters)

In [8]:
text = "PythonA"
print(' The string is ', text)
print("First character:", text[0])
print("Last character:", text[-1])
print("3rd character:", text[2])

 The string is  PythonA
First character: P
Last character: A
3rd character: t

In [9]:
print('Actual String ', text, ' Reverse String is ', text[3::-1])

Actual String  PythonA  Reverse String is  htyP

In [10]:
print('Actual String ', text, ' Reverse String is ', text[::-1])

Actual String  PythonA  Reverse String is  AnohtyP

In [11]:
print("Middle character:", text[round(len(text)/2)-1])

Middle character: h

5. Slicing (Get part of string)
# string[start:stop:step]

In [12]:
print("First 3 chars:", text[0:3])
print("From index 2:", text[2:])
print("Reverse string:", text[::-1])

First 3 chars: Pyt
From index 2: thonA
Reverse string: AnohtyP

In [13]:
name = "  dAta science 1syed hasan "
print("Original String with spaces - ", name)
print("Upper:", name.upper())
print("Lower:", name.lower())
print("Strip spaces:", name.strip())
#print("Sentence case :" , name.capitalize())
print("title case :" , name.title())
print("Replace:", name.replace("science", "analysis"))

Original String with spaces -    dAta science 1syed hasan
Upper:   DATA SCIENCE 1SYED HASAN
Lower:   data science 1syed hasan
Strip spaces: dAta science 1syed hasan
title case :   Data Science 1Syed Hasan
Replace:   dAta analysis 1syed hasan

# 7. Checking Content

In [14]:
sample = "Python123"
print("Is alphabet:", sample.isalpha())
print("Is digit:", sample.isdigit())
print("Is alphanumeric:", sample.isalnum())

Is alphabet: False
Is digit: False
Is alphanumeric: True

 # 8. Splitting and Joining

In [16]:
sentence = "Python is easy to learn"
print(' the Sentence is ', sentence)
words = sentence.split(" ")
print("Split:", words)
joined = "*".join(words)
print("Joined:", joined)

 the Sentence is  Python is easy to learn
Split: ['Python', 'is', 'easy', 'to', 'learn']
Joined: Python*is*easy*to*learn

# 9. String Formatting

In [17]:
name = "Taheera"
age = 25
gender ='F'
city ='New York'
# Old style
print("My name is %s and I am %d years old, and my gender is %s" % (name, age,gender))
# format()
print("My name is {} and I am {} years old, with gender is {} and city in {}".format(name, age, gender, city))
# f-string (recommended)
print(f"My gender is {gender}, name is {name} and I am {age} years old")

My name is Taheera and I am 25 years old, and my gender is F
My name is Taheera and I am 25 years old, with gender is F and city in New York
My gender is F, name is Taheera and I am 25 years old

# 11. Most Important Concept: Strings are Immutable

In [18]:
text = "hello"
# text[0] = 'H'  # ❌ This will give an error
# Correct way:
text = "H" + text[1:]
print("Modified string:", text)
print("He said \"Python is fun\"")  #double quotes

Modified string: Hello
He said "Python is fun"

# 12. Length of String

In [19]:
print("Length of 'Python':", len("Python"))

Length of 'Python': 6

# 13. Membership (in keyword)

In [20]:
print("Py" in "Python")
print("Java" not in "Python")

True
True

In [21]:
import pandas as pd
from pydataset import data

# Create mtcars dataset with car names

In [22]:
data = {
    "car_name": [ "Mazda RX4", "Mazda RX4    Wag", "Datsun 710","Hornet 4 Drive", "Hornet   Sportabout  ", "Valiant", "Duster 360", "merc 240D", "Merc 230", "Merc 280" ],
    "mpg": [21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2]}
df = pd.DataFrame(data)
print("Original Data:\n", df)

Original Data:
                 car_name   mpg
0              Mazda RX4  21.0
1       Mazda RX4    Wag  21.0
2             Datsun 710  22.8
3         Hornet 4 Drive  21.4
4  Hornet   Sportabout    18.7
5                Valiant  18.1
6             Duster 360  14.3
7              merc 240D  24.4
8               Merc 230  22.8
9               Merc 280  19.2

# Search

In [23]:
mazda_cars = df[df['car_name'].str.contains("Mazda")]
print("\nCars with 'Mazda':\n", mazda_cars)
# .str.contains() → pattern search
# Case sensitive by default

Cars with 'Mazda':
            car_name   mpg
0         Mazda RX4  21.0
1  Mazda RX4    Wag  21.0

In [24]:
df[df['car_name'].str.contains("Merc", case=True)]

   car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [25]:
df[df['car_name'].str.contains("merc", case=False)]
# case insenstive

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

# FILTER (Start / End patterns
# Cars starting with “Merc”

In [26]:
merc_cars = df[df['car_name'].str.startswith("Merc")]
print("\nCars starting with 'Merc':\n", merc_cars)

Cars starting with 'Merc':
    car_name   mpg
8  Merc 230  22.8
9  Merc 280  19.2

In [27]:
df[df['car_name'].str.startswith(("Merc",'merc'))]

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

In [28]:
df[df['car_name'].str.startswith(("Merc",'merc'))]

    car_name   mpg
7  merc 240D  24.4
8   Merc 230  22.8
9   Merc 280  19.2

# Replace Strings

In [29]:
df['car_name_updated'] = df['car_name'].str.replace("Merc", "Mercedes", regex=False)
print("\nUpdated Names:\n", df[['car_name', 'car_name_updated']])

Updated Names:
                 car_name       car_name_updated
0              Mazda RX4              Mazda RX4
1       Mazda RX4    Wag       Mazda RX4    Wag
2             Datsun 710             Datsun 710
3         Hornet 4 Drive         Hornet 4 Drive
4  Hornet   Sportabout    Hornet   Sportabout
5                Valiant                Valiant
6             Duster 360             Duster 360
7              merc 240D              merc 240D
8               Merc 230           Mercedes 230
9               Merc 280           Mercedes 280

In [30]:
df['car_name'].str.replace("Merc", "Mercedes", case=False, regex=False)

0                Mazda RX4
1         Mazda RX4    Wag
2               Datsun 710
3           Hornet 4 Drive
4    Hornet   Sportabout
5                  Valiant
6               Duster 360
7            Mercedes 240D
8             Mercedes 230
9             Mercedes 280
Name: car_name, dtype: object

# Split /Breaks

In [31]:
df['brand'] = df['car_name'].str.split().str[0]
print("\nExtracted Brand:\n", df[['car_name', 'brand']])
#👉 Very useful for: * extracting categories, * feature engineering

Extracted Brand:
                 car_name    brand
0              Mazda RX4    Mazda
1       Mazda RX4    Wag    Mazda
2             Datsun 710   Datsun
3         Hornet 4 Drive   Hornet
4  Hornet   Sportabout     Hornet
5                Valiant  Valiant
6             Duster 360   Duster
7              merc 240D     merc
8               Merc 230     Merc
9               Merc 280     Merc

# Change Case

In [32]:
df['upper_name'] = df['car_name'].str.upper()
df['lower_name'] = df['car_name'].str.lower()
df

,car_name,mpg,car_name_updated,brand,upper_name,lower_name
0,Mazda RX4,21.0,Mazda RX4,Mazda,MAZDA RX4,mazda rx4
1,Mazda RX4 Wag,21.0,Mazda RX4 Wag,Mazda,MAZDA RX4 WAG,mazda rx4 wag
2,Datsun 710,22.8,Datsun 710,Datsun,DATSUN 710,datsun 710
3,Hornet 4 Drive,21.4,Hornet 4 Drive,Hornet,HORNET 4 DRIVE,hornet 4 drive
4,Hornet Sportabout,18.7,Hornet Sportabout,Hornet,HORNET SPORTABOUT,hornet sportabout
5,Valiant,18.1,Valiant,Valiant,VALIANT,valiant
6,Duster 360,14.3,Duster 360,Duster,DUSTER 360,duster 360
7,merc 240D,24.4,merc 240D,merc,MERC 240D,merc 240d
8,Merc 230,22.8,Mercedes 230,Merc,MERC 230,merc 230
9,Merc 280,19.2,Mercedes 280,Merc,MERC 280,merc 280